.tpl_web_build:
  stage: build-web
  image: node:16
  rules:
    - when: manual
  before_script:
    # - apk add --no-cache build-base autoconf automake python3 nasm gettext libzip-dev vips-dev
    - apt update
    - apt install build-essential
  artifacts:
    untracked: true
    paths:
      - build/
      - android/
  # tags:
  #   - artifacts

build:web:prod:
  extends: .tpl_web_build
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /-rc\d+$/
  script:
    - echo "$DOTENV_PROD" > .env
    - echo "$SENTRY_CLI_CONFIG" > .sentryclirc
    - cp capacitor.config.json.dist capacitor.config.json
    - yarn install --frozen-lockfile --non-interactive --prod
    - yarn add @sentry/cli
    - yarn build
    - npx sentry-cli releases new $CI_COMMIT_TAG
    - npx sentry-cli releases files $CI_COMMIT_TAG upload-sourcemaps ./build/assets/js
    - npx sentry-cli releases finalize $CI_COMMIT_TAG
    - npx cap sync android

build:web:stage:
  extends: .tpl_web_build
  rules:
    - if: $CI_COMMIT_TAG =~ /-rc\d+$/
  script:
    - echo "$DOTENV_STAGE_K8S" > .env
    - echo "$SENTRY_CLI_CONFIG" > .sentryclirc
    - cp capacitor.config.json.dist capacitor.config.json
    - yarn install --frozen-lockfile --non-interactive --prod
    - yarn add @sentry/cli
    - yarn build
    - npx sentry-cli releases new $CI_COMMIT_TAG
    - npx sentry-cli releases files $CI_COMMIT_TAG upload-sourcemaps ./build/assets/js
    - npx sentry-cli releases finalize $CI_COMMIT_TAG
    - npx cap sync android

build:web:dev:
  extends: .tpl_web_build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  script:
    - echo "$DOTENV_DEV" > .env
    - cp capacitor.config.json.dist capacitor.config.json
    - yarn install --frozen-lockfile --non-interactive --prod
    - yarn build-dev
    - npx cap sync android
