apiVersion: v1
kind: Service
metadata:
  name: {{ include "zmq.fullname" . }}
  labels:
    {{- include "zmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: zmq
  selector:
    {{- include "zmq.selectorLabels" . | nindent 4 }}
