export const TYPE_SHOW_TRIGGER_EDITOR = 'TYPE_SHOW_TRIGGER_EDITOR'
export const TYPE_HIDE_TRIGGER_EDITOR = 'TYPE_HIDE_TRIGGER_EDITOR'

export const TYPE_SET_TRIGGER = 'TYPE_SET_TRIGGER'

export const TYPE_SET_TRIGGER_CONDITION = 'TYPE_SET_TRIGGER_CONDITION'
export const TYPE_SET_TRIGGER_ACTIONS = 'TYPE_SET_TRIGGER_ACTIONS'
export const TYPE_ADD_TRIGGER_ACTION = 'TYPE_ADD_TRIGGER_ACTION'
export const TYPE_REMOVE_TRIGGER_ACTION = 'TYPE_REMOVE_TRIGGER_ACTION'
