apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-getsober-one
  namespace: soberone
spec:
  commonName: app.getsober.one
  dnsNames:
  - app.getsober.one
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: app-getsober-one-tls
