stages:
  - build
  - deploy

.tpl_build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

build:
  extends: .tpl_build
  only:
    - tags
  variables:
    API_BASE_URL: https://api-scw.getsober.one
  script:
    - >
      /kaniko/executor
      --context=${CI_PROJECT_DIR}
      --dockerfile=${CI_PROJECT_DIR}/Dockerfile
      --destination="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      --destination="$CI_REGISTRY_IMAGE:latest"
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg API_BASE_URL=$API_BASE_URL
      --cache=true
  tags:
    - docker
