export const footerMenu = [
  {
    id: 1,
    location: 'footer',
    icon: 'home',
    link: '/',
    title: 'menu.home',
    visible: true,
    disabled: false,
    order: 1,
  },
  {
    id: 2,
    location: 'footer',
    icon: 'tasks',
    link: '/tasks',
    title: 'menu.tasks',
    visible: true,
    disabled: false,
    order: 2,
  },
  {
    id: 11,
    location: 'footer',
    icon: 'content',
    link: '/tools/diary',
    title: 'menu.diary',
    visible: true,
    disabled: false,
    order: 3,
  },
  {
    id: 13,
    location: 'footer',
    icon: 'donate',
    link: '/helpus',
    title: 'menu.donate',
    visible: true,
    disabled: false,
    order: 4,
  },
]

export const moreMenu = [
  {
    id: 7,
    location: 'more',
    icon: 'tools',
    link: '/tools/tests',
    title: 'menu.tests',
    visible: true,
    disabled: false,
    order: 1,
  }, {
    id: 12,
    location: 'more',
    icon: 'star',
    link: 'https://coda.io/@oleg-ovsyannikov/sober-faq',
    title: 'menu.faq',
    visible: true,
    disabled: false,
    order: 2,
  }, {
    id: 4,
    location: 'more',
    icon: 'chat',
    link: '#',
    title: 'menu.support.title',
    description: 'menu.support.description',
    visible: true,
    disabled: false,
    order: 3,
  }, {
    id: 10,
    location: 'more',
    icon: 'profile',
    link: '/profile/edit',
    title: 'menu.editProfile',
    visible: true,
    disabled: false,
    order: 4,
  }, {
    id: 8,
    location: 'more',
    icon: 'settings',
    link: '/profile/settings',
    title: 'menu.settings',
    visible: true,
    disabled: false,
    order: 5,
  }
]
