apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: centrifugo-scw-getsober-one
  namespace: soberone
spec:
  commonName: centrifugo-scw.getsober.one
  dnsNames:
  - centrifugo-scw.getsober.one
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: centrifugo-scw-getsober-one-tls
