apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: monitoring
spec:
  commonName: grafana.getsober.one
  dnsNames:
  - grafana.getsober.one
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: grafana-tls
