export const FETCHING_DIARY = 'FETCHING_DIARY'
export const FETCHED_DIARY = 'FETCHED_DIARY'
export const FETCH_DIARY_FAIL = 'FETCH_DIARY_FAIL'

export const FETCHING_DIARY_ITEM = 'FETCHING_DIARY_ITEM'
export const FETCHED_DIARY_ITEM = 'FETCHED_DIARY_ITEM'
export const FETCH_DIARY_ITEM_FAIL = 'FETCH_DIARY_ITEM_FAIL'

export const UPDATING_DIARY_ITEM = 'UPDATING_DIARY_ITEM'
export const UPDATED_DIARY_ITEM = 'UPDATED_DIARY_ITEM'
export const UPDATE_DIARY_ITEM_FAIL = 'UPDATE_DIARY_ITEM_FAIL'

export const CREATING_DIARY_ITEM = 'CREATING_DIARY_ITEM'
export const CREATED_DIARY_ITEM = 'CREATED_DIARY_ITEM'
export const CREATE_DIARY_ITEM_FAIL = 'CREATE_DIARY_ITEM_FAIL'
