export const FETCHING_TEST_LIST = 'FETCHING_TEST_LIST'
export const FETCHED_TEST_LIST = 'FETCHED_TEST_LIST'
export const FETCH_TEST_LIST_FAIL = 'FETCH_TEST_LIST_FAIL'

export const FETCHING_TEST_DETAILS = 'FETCHING_TEST_DETAILS'
export const FETCHED_TEST_DETAILS = 'FETCHED_TEST_DETAILS'
export const FETCH_TEST_DETAILS_FAIL = 'FETCH_TEST_DETAILS_FAIL'

export const UPDATING_TEST_DETAILS = 'UPDATING_TEST_DETAILS'
export const UPDATED_TEST_DETAILS = 'UPDATED_TEST_DETAILS'
export const UPDATE_TEST_DETAILS_FAIL = 'UPDATE_TEST_DETAILS_FAIL'

export const SUBMITTING_TEST_RESULT = 'SUBMITTING_TEST_RESULT'
export const SUBMITTED_TEST_RESULT = 'SUBMITTED_TEST_RESULT'
export const SUBMIT_TEST_RESULT_FAIL = 'SUBMIT_TEST_RESULT_FAIL'
