export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const PASSWORD_REMINDER_REQUEST = 'PASSWORD_REMINDER_REQUEST'
export const PASSWORD_REMINDER_SUCCESS = 'PASSWORD_REMINDER_SUCCESS'
export const PASSWORD_REMINDER_FAIL = 'PASSWORD_REMINDER_FAIL'
export const LOGOUT = 'LOGOUT'

export const FETCHING_USER_INFO = 'FETCHING_USER_INFO'
export const FETCHED_USER_INFO = 'FETCHED_USER_INFO'
export const FETCH_USER_INFO_FAIL = 'FETCH_USER_INFO_FAIL'

export const UPDATING_USER_INFO = 'UPDATING_USER_INFO'
export const UPDATED_USER_INFO = 'UPDATED_USER_INFO'
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL'

export const CONFIRM_EMAIL_SUCCESS = 'CONFIRM_EMAIL_SUCCESS'
export const CONFIRM_EMAIL_FAIL = 'CONFIRM_EMAIL_FAIL'

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_JWT = 'UPDATE_JWT'
export const UPDATE_JWT_TOKEN = 'UPDATE_JWT_TOKEN'
