# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
use_frameworks!

project 'Sober One iOS App.xcodeproj'

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAppleSignIn', :path => '../../node_modules/@capacitor-community/apple-sign-in'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/@capacitor/push-notifications'
end

target 'Sober One iOS App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  capacitor_pods

  # Pods for Privilege
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.2.7'
  pod 'Intercom'
  pod 'GoogleSignIn'
  pod 'VK-ios-sdk'
  pod 'SwiftyVK'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Amplitude', '~> 8.3.0'
  pod 'AppsFlyerFramework'
end
