apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n
  namespace: n8n
spec:
  commonName: n8n.getsober.one
  dnsNames:
  - n8n.getsober.one
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: n8n-tls