apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-old
  namespace: soberone
spec:
  commonName: admin-old.getsober.one
  dnsNames:
  - admin-old.getsober.one
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: admin-old-tls